package br.univali.tccbackend.pmd;

class FeatureEnvy extends PmdTest {

  @Override
  String getInputCode() {
    return "public class Foo {\n"
        + "\n"
        + "  A getA() {\n"
        + "    return new A();\n"
        + "  }\n"
        + "\n"
        + "  B getB() {\n"
        + "    return new B();\n"
        + "  }\n"
        + "\n"
        + "  C getC() {\n"
        + "    return new C();\n"
        + "  }\n"
        + "\n"
        + "  D getD() {\n"
        + "    return new D();\n"
        + "  }\n"
        + "\n"
        + "  E getE() {\n"
        + "    return new E();\n"
        + "  }\n"
        + "\n"
        + "  F getF() {\n"
        + "    return new F();\n"
        + "  }\n"
        + "\n"
        + "  G getG() {\n"
        + "    return new G();\n"
        + "  }\n"
        + "\n"
        + "  H getH() {\n"
        + "    return new H();\n"
        + "  }\n"
        + "\n"
        + "  I getI() {\n"
        + "    return new I();\n"
        + "  }\n"
        + "\n"
        + "  J getJ() {\n"
        + "    return new J();\n"
        + "  }\n"
        + "\n"
        + "  K getK() {\n"
        + "    return new K();\n"
        + "  }\n"
        + "\n"
        + "  L getL() {\n"
        + "    return new L();\n"
        + "  }\n"
        + "\n"
        + "  M getM() {\n"
        + "    return new M();\n"
        + "  }\n"
        + "\n"
        + "  N getN() {\n"
        + "    return new N();\n"
        + "  }\n"
        + "\n"
        + "  O getO() {\n"
        + "    return new O();\n"
        + "  }\n"
        + "\n"
        + "  P getP() {\n"
        + "    return new P();\n"
        + "  }\n"
        + "\n"
        + "  Q getQ() {\n"
        + "    return new Q();\n"
        + "  }\n"
        + "\n"
        + "  R getR() {\n"
        + "    return new R();\n"
        + "  }\n"
        + "\n"
        + "  S getS() {\n"
        + "    return new S();\n"
        + "  }\n"
        + "\n"
        + "  T getT() {\n"
        + "    return new T();\n"
        + "  }\n"
        + "\n"
        + "  U getU() {\n"
        + "    return new U();\n"
        + "  }\n"
        + "  \n"
        + "}\n";
  }

  @Override
  String getExpectedResult() {
    return "{\"formatVersion\":0,"
        + "\"pmdVersion\":\"" + PMD_VERSION + "\","
        + "\"timestamp\":\"\","
        + "\"files\":["
        + "{\"filename\":\"\","
        + "\"violations\":["
        + "{\"beginline\":1,"
        + "\"begincolumn\":1,"
        + "\"endline\":87,"
        + "\"endcolumn\":2,"
        + "\"description\":\"High amount of different objects as members denotes a high coupling\","
        + "\"rule\":\"CouplingBetweenObjects\","
        + "\"ruleset\":\"Design\","
        + "\"priority\":3,"
        + "\"externalInfoUrl\":\"" + PMD_RULES_URL + "#couplingbetweenobjects\"}]}],"
        + "\"suppressedViolations\":[],"
        + "\"processingErrors\":[],"
        + "\"configurationErrors\":[]}";
  }
}
